version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Java code...
      - javac -cp "lib/*" src/main/java/com/example/servlet/*.java
      - echo Creating WAR file...
      - jar -cvf AozoraBookSelector.war -C src/main/webapp .
      - echo Build completed on `date`
artifacts:
  files:
    - AozoraBookSelector.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no 